openapi: 3.0.0
info:
  version: 1.0.0
  title: Batch Status API v1.0
  description: ""
tags:
  - name: Batch Status
paths:
  /api/v1/batch:
    get:
      tags:
        - Batch Status
      operationId: getBatches
      description: Fetch all batches with some optional filters
      parameters:
        - in: header
          name: authorization
          description: The access token associated to the session. IDAM_SYSTEM_OWNER role
            is required.
          required: true
          schema:
            type: string
        - in: query
          name: status
          required: false
          description: Optional parameter allowing filtering by batch status.
          schema:
            type: string
        - in: query
          name: clientId
          required: false
          description: Optional parameter allowing filtering by clientId.
          schema:
            type: string
        - name: size
          in: query
          description: The number of items per page, default of 20
          required: false
          example: 20
          schema:
            type: integer
            format: int32
        - name: page
          in: query
          description: The index of the page of items, starting at 0 for the first page
          required: false
          example: 10
          schema:
            type: integer
            format: int32
      responses:
        "200":
          description: Request accepted.
          content:
            "*/*":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BatchResponse"
        "400":
          description: Parameters are invalid.
        "401":
          description: Missing bearer token.
        "403":
          description: Bearer token is expired, or it doesn't have the required scopes.
  "/api/v1/batch/{batchId}":
    get:
      tags:
        - Batch Status
      operationId: batchStatus
      description: Get the latest state of an accepted batch request.
      parameters:
        - in: header
          name: authorization
          description: The access token associated to the session.
          required: true
          schema:
            type: string
        - in: path
          name: batchId
          required: true
          description: The id of the batch process.
          schema:
            type: string
      responses:
        "200":
          description: Request accepted.
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/BatchStatusResponse"
        "400":
          description: Required parameters are missing or invalid.
        "401":
          description: Missing bearer token.
        "403":
          description: Bearer token is expired, or it doesn't have the required scopes.
        "404":
          description: Batch not found.
    post:
      tags:
        - Batch Status
      operationId: runBatch
      description: Executes the target batch job.
      parameters:
        - in: header
          name: authorization
          description: The access token associated to the session.
          required: true
          schema:
            type: string
        - in: path
          name: batchId
          required: true
          description: The id of the batch process.
          schema:
            type: string
      responses:
        "200":
          description: Request accepted.
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/BatchResponse"
        "400":
          description: Required parameters are missing or invalid.
        "401":
          description: Missing bearer token.
        "403":
          description: Bearer token is expired, or it doesn't have the required scopes.
        "404":
          description: Batch not found.
    delete:
      tags:
        - Batch Status
      operationId: cancelBatch
      description: Cancel a batch operation.
      parameters:
        - in: header
          name: authorization
          description: The access token associated to the session.
          required: true
          schema:
            type: string
        - in: path
          name: batchId
          required: true
          description: The id of the batch process.
          schema:
            type: string
      responses:
        "204":
          description: Success.
        "400":
          description: Required parameters are missing or invalid.
        "401":
          description: Missing bearer token.
        "403":
          description: Bearer token is expired, or it doesn't have the required scopes.
        "404":
          description: Batch not found.
servers:
  - url: /api/v1
components:
  securitySchemes:
    auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: http://authserver/login
          tokenUrl: http://authserver/oauth2/token
          scopes: {}
  schemas:
    BatchResponse:
      type: object
      properties:
        id:
          type: string
          description: Batch Unique ID
        state:
          type: string
          enum:
            - ACCEPTED
            - IN_PROGRESS
            - COMPLETE
            - CANCELLED
        creationDate:
          type: string
          description: DateTime this was created.
        lastModifiedDate:
          type: string
          description: DateTime this was last updated created.
        requestClientId:
          type: string
          description: Client ID in the access_token used for the request.
        requestUserId:
          type: string
          description: User ID of the requestor.
        processorId:
          type: string
          description: ID of the batch processor that has picked up the batch for
            processing.
    BatchStatusResponse:
      type: object
      properties:
        createdAt:
          type: string
          description: A timestamp of the created datetime of the batch process
        status:
          type: string
          enum:
            - ACCEPTED
            - IN_PROGRESS
            - COMPLETE
            - CANCELLED
        totalRequests:
          type: integer
          description: Total number of requested operations
        success:
          type: integer
          description: Total number of successful requested operations processed
        failed:
          type: integer
          description: Total number of failed requested operations processed
        response:
          type: array
          items:
            $ref: "#/components/schemas/BatchRequestResponseItem"
          description: The names of the roles to be assigned to the user
    BatchRequestResponseItem:
      type: object
      properties:
        statusCode:
          type: integer
          description: The status code response for the processed request.
        status:
          type: string
          description: The status response message of the processed request.
        path:
          type: string
          description: A location where the processed item may be retrieved.
        errorMessages:
          type: array
          description: An array of reasons as to why the request failed
          items:
            type: string